version: '3.9'

services:
  proxy:
    image: yandeu/postgres-browser-proxy:latest
    environment:
      HOST: 0.0.0.0
      PG_HOST: db
      PG_USER: postgres
      PG_PASSWORD: mysecretpassword
    ports:
      - '3000:3000'
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 16M
        reservations:
          memory: 4M
      replicas: 2

  db:
    image: postgis/postgis:15-3.3-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M
      replicas: 1
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 5s
