services:
  proxy:
    image: yandeu/postgres-browser-proxy
    environment:
      HOST: db
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgis/postgis:15-3.3-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
