# read: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Docker

on:
  push:
    branches:
      - main

env:
  RUSTFLAGS: '-Dwarnings'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          target: x86_64-unknown-linux-musl
          override: true

      - name: Parse README.md
        run: |
          npm ci
          node ./scripts/parse-md.mjs

      - name: Run Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target x86_64-unknown-linux-musl

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: yandeu/postgres-browser-proxy:latest
